Omega:
  TimeManagement:
    StartTime: 0001-01-01_00:00:00
    StopTime: 0001-01-01_02:00:00
    RunDuration: none
    CalendarType: No Leap
  TimeIntegration:
    TimeStepper: Forward-Backward
    TimeStep: 0000_00:10:00
  Dimension:
    NVertLevels: 60
  Decomp:
    HaloWidth: 3
    DecompMethod: MetisKWay
  State:
    NTimeLevels: 2
  Advection:
    FluxThicknessType: Center
  Tendencies:
    ThicknessFluxTendencyEnable: true
    PVTendencyEnable: true
    KETendencyEnable: true
    SSHTendencyEnable: true
    VelDiffTendencyEnable: true
    ViscDel2: 1.0e3
    VelHyperDiffTendencyEnable: true
    ViscDel4: 1.2e11
  IOStreams:
    InitialState:
      UsePointerFile: false
      Filename: OmegaMesh.nc
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: OnStartup
      UseStartEnd: false
      Contents:
        - Restart
    RestartWrite:
      UsePointerFile: true
      PointerFilename: ocn.pointer
      Filename: ocn.restart.$Y-$M-$D_$h.$m.$s
      Mode: write
      IfExists: replace
      Precision: double
      Freq: 6
      FreqUnits: months
      UseStartEnd: false
      Contents:
        - Restart
    RestartReadTest:
      UsePointerFile: true
      PointerFilename: ocn.pointer
      Mode: read
      Precision: double
      Freq: 6
      FreqUnits: months
      UseStartEnd: false
      Contents:
        - Restart
    History:
      UsePointerFile: false
      Filename: ocn.hist.$SimTime
      Mode: write
      IfExists: replace
      Precision: double
      Freq: 1
      FreqUnits: months
      UseStartEnd: false
      Contents:
        - Tracers
    Highfreq:
      UsePointerFile: false
      Filename: ocn.hifreq.$Y-$M-$D_$h.$m.$s
      Mode: write
      IfExists: replace
      Precision: single
      Freq: 10
      FreqUnits: days
      UseStartEnd: true
      StartTime: 0001-06-01_00.00.00
      EndTime: 0001-06-30_00.00.00
      Contents:
        - Tracers
  Tracers:
    Base: [Temp, Salt]
    Debug: [Debug1, Debug2, Debug3]
